import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

function read(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8')
}

function exists(relativePath) {
  return existsSync(new URL(relativePath, import.meta.url))
}

test('theme toggle renders an appearance popover with palette and mode choices', () => {
  const source = read('../components/ThemeToggle.vue')

  assert.match(source, /class="appearance-trigger"/)
  assert.match(source, /外观/)
  assert.match(source, /themeStore\.palettes/)
  assert.match(source, /themeStore\.modes/)
  assert.match(source, /setPalette/)
  assert.match(source, /setMode/)
  assert.match(source, /class="palette-swatch"/)
})

test('theme css defines fixed palette packages and reduced motion support', () => {
  const theme = read('../styles/theme.css')
  const global = read('../styles/global.css')
  const login = read('../views/Login.vue')
  const register = read('../views/Register.vue')

  assert.match(theme, /\[data-palette="juniper"\]/)
  assert.match(theme, /\[data-palette="fog"\]/)
  assert.match(theme, /\[data-palette="copper"\]/)
  assert.match(theme, /\[data-theme="dark"\]/)
  assert.match(theme, /\[data-palette="fog"\]\[data-theme="dark"\]/)
  assert.match(theme, /\[data-palette="copper"\]\[data-theme="dark"\]/)
  assert.match(theme, /--theme-grid-x/)
  assert.match(theme, /--header-backdrop-bg/)
  assert.match(theme, /--el-color-primary:\s*var\(--primary-color\)/)
  assert.match(theme, /--el-bg-color:\s*var\(--panel-bg\)/)
  assert.match(theme, /--el-text-color-primary:\s*var\(--text-color\)/)
  assert.match(global, /prefers-reduced-motion:\s*reduce/)
  assert.doesNotMatch(global, /rgba\(47,\s*128,\s*237,\s*0\.08\)/)
  assert.doesNotMatch(global, /rgba\(47,\s*128,\s*237,\s*0\.06\)/)
  assert.match(global, /--el-table-header-bg-color:\s*color-mix\(in srgb,\s*var\(--primary-color\)\s*6%,\s*var\(--panel-bg\)\)/)
  assert.match(global, /--el-table-row-hover-bg-color:\s*color-mix\(in srgb,\s*var\(--primary-color\)\s*6%,\s*var\(--panel-bg\)\)/)
  assert.doesNotMatch(login, /rgba\(47,\s*128,\s*237,\s*0\.06\)/)
  assert.doesNotMatch(register, /rgba\(47,\s*128,\s*237,\s*0\.06\)/)
  assert.match(login, /var\(--theme-grid-x\)/)
  assert.match(login, /var\(--theme-grid-y\)/)
  assert.match(register, /var\(--theme-grid-x\)/)
  assert.match(register, /var\(--theme-grid-y\)/)
})

test('app header uses a full-width translucent sticky backdrop without top gap', () => {
  const source = read('../components/AppHeader.vue')

  assert.match(source, /\.app-header::before/)
  assert.match(source, /\.app-header::after/)
  assert.match(source, /\.app-header::before\s*\{[\s\S]*left:\s*0;[\s\S]*right:\s*0;[\s\S]*width:\s*auto;[\s\S]*pointer-events:\s*none;/)
  assert.match(source, /\.app-header::after\s*\{[\s\S]*left:\s*0;[\s\S]*right:\s*0;[\s\S]*width:\s*auto;[\s\S]*pointer-events:\s*none;/)
  assert.match(source, /backdrop-filter:\s*blur/)
  assert.match(source, /mask-image:\s*linear-gradient/)
  assert.match(source, /top:\s*0/)
  assert.doesNotMatch(source, /width:\s*100vw/)
  assert.doesNotMatch(source, /border-radius:\s*0 0 24px 24px/)
})

test('app header brand mark uses the visual refresh wordmark system', () => {
  const source = read('../components/AppHeader.vue')

  assert.match(source, /class="logo-copy"/)
  assert.match(source, /class="logo-kicker"/)
  assert.match(source, /\.logo::before/)
  assert.match(source, /\.logo-mark::after/)
  assert.match(source, /\.logo-text\s*\{[^}]*font-family:\s*Georgia/)
  assert.match(source, /\.logo-mark\s*\{[^}]*background:\s*color-mix\(in srgb,\s*var\(--primary-color\)\s*10%,\s*var\(--panel-bg\)\)/)
  assert.match(source, /\.logo-kicker\s*\{[^}]*color:\s*var\(--muted-text-color\)/)
  assert.doesNotMatch(source, /<span class="logo-mark">B<\/span>/)
  assert.doesNotMatch(source, /\.logo-mark\s*\{[^}]*background:\s*var\(--primary-color\)/)
})

test('global background keeps the prototype grid visible across light and dark themes', () => {
  const theme = read('../styles/theme.css')

  assert.match(theme, /body\s*\{[\s\S]*linear-gradient\(90deg,\s*var\(--theme-grid-x\)\s*1px,\s*transparent\s*1px\)/)
  assert.match(theme, /body\s*\{[\s\S]*linear-gradient\(180deg,\s*var\(--theme-grid-y\)\s*1px,\s*transparent\s*1px\)/)
  assert.match(theme, /background-size:\s*44px 44px/)
  assert.doesNotMatch(
    theme,
    /body\s*\{[\s\S]*linear-gradient\(180deg,\s*color-mix\(in srgb,\s*var\(--panel-bg\)\s*82%,\s*transparent\),\s*var\(--bg-color\)\)/
  )
})

test('home page uses the prototype index composition instead of the old hero card layout', () => {
  const source = read('../views/Home.vue')

  assert.match(source, /class="index-hero"/)
  assert.match(source, /class="signal-panel"/)
  assert.match(source, /class="toolbar"/)
  assert.match(source, /class="content-grid"/)
  assert.match(source, /class="article-entry"/)
  assert.doesNotMatch(source, /hero-board|hero-panel|spotlight-card|content-layout/)
  assert.doesNotMatch(source, /<ArticleCard\b/)
})

test('home page exposes readable seven-day content signal instead of reading ranking', () => {
  const source = read('../views/Home.vue')

  assert.match(source, /contentSignal/)
  assert.match(source, /近 7 天更新/)
  assert.match(source, /aria-label="近 7 天更新"/)
  assert.match(source, /signal-panel/)
  assert.match(source, /signal-bars/)
  assert.match(source, /signal-day/)
  assert.match(source, /signal-day-label/)
  assert.match(source, /signal-chart-note/)
  assert.match(source, /contentSignal\.chartLabel/)
  assert.match(source, /day\.accessibleLabel/)
  assert.match(source, /day\.weekdayLabel/)
  assert.match(source, /is-today/)
  assert.match(source, /is-peak/)
  assert.match(source, /柱高 = 更新篇数/)
  assert.match(source, /buildContentSignal/)
  assert.doesNotMatch(source, /filterSummary/)
  assert.doesNotMatch(source, /本周内容信号/)
  assert.doesNotMatch(source, /本周阅读信号/)
  assert.doesNotMatch(source, /\.signal-bar:nth-child\(4\)/)
  assert.doesNotMatch(source, /signal-strip/)
  assert.doesNotMatch(source, /signal-card/)
  assert.doesNotMatch(source, /已读/)
  assert.doesNotMatch(source, /hot|ranking|热门|排行/)
  assert.doesNotMatch(source, /featuredArticle\.viewCount/)
  assert.doesNotMatch(source, /viewCount\s*\|\|\s*0/)
  assert.match(source, /formatDate\(article\.updatedAt \|\| article\.createdAt\)/)
  assert.doesNotMatch(source, /formatDate\(article\.createdAt\)/)
})

test('article cards include focused line and reduced motion styling', () => {
  const source = read('../components/ArticleCard.vue')

  assert.match(source, /<article\b[\s\S]*class="article-card article-entry"/)
  assert.match(source, /\.article-card::before/)
  assert.match(source, /transform:\s*scaleY/)
  assert.match(source, /theme-glow-color/)
  assert.match(source, /prefers-reduced-motion:\s*reduce/)
  assert.doesNotMatch(source, /<el-card\b/)
  assert.doesNotMatch(source, /:deep\(\.el-card__body\)/)
  assert.doesNotMatch(source, /viewCount/)
  assert.doesNotMatch(source, />\s*阅读\s*\{\{\s*article\.viewCount\s*\|\|\s*0\s*\}\}\s*</)
})

test('article detail styles toc active indicator and themed resume dialog', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /\.toc-link::before/)
  assert.match(source, /\.toc-link\.active::before/)
  assert.match(source, /resume-reading-dialog/)
  assert.match(source, /theme-glow-color/)
})

test('article detail uses the reading-surface prototype skeleton', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /class="detail-head"/)
  assert.match(source, /class="detail-actions"/)
  assert.match(source, /class="detail-meta"/)
  assert.match(source, /class="reading-primary"/)
  assert.match(source, /class="reading-canvas"/)
  assert.match(source, /class="article-body"/)
  assert.doesNotMatch(source, /class="article-hero"/)
  assert.doesNotMatch(source, /class="reading-summary"/)
  assert.doesNotMatch(source, /class="detail-side"/)
  assert.doesNotMatch(source, /class="section-meter"/)
  assert.doesNotMatch(source, /class="meter-dot"/)
})

test('article detail gives the article body a quiet primary reading surface', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /\.article-body\s*\{[^}]*min-height:\s*clamp\(360px,\s*42vh,\s*560px\);/)
  assert.match(source, /\.article-body\s*\{[^}]*border:\s*1px solid var\(--border-color\);/)
  assert.match(source, /\.article-body\s*\{[^}]*border-radius:\s*var\(--radius-md\);/)
  assert.match(source, /\.article-body\s*\{[^}]*background:\s*color-mix\(in srgb,\s*var\(--panel-bg\)\s*92%,\s*transparent\);/)
  assert.match(source, /\.article-body\s*\{[^}]*box-shadow:\s*0 18px 46px color-mix\(in srgb,\s*var\(--text-color\)\s*7%,\s*transparent\);/)
  assert.match(source, /\.note-panel\s*\{[^}]*background:\s*transparent;/)
  assert.match(source, /\.note-panel\s*\{[^}]*box-shadow:\s*none;/)
  assert.doesNotMatch(source, /\.article-body\s*\{[^}]*border-top:/)
  assert.doesNotMatch(source, /\.article-body\s*\{[^}]*border-bottom:/)
})

test('article detail hero follows the open prototype briefing layout', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /<div class="reading-canvas">[\s\S]*?<div class="reading-primary">[\s\S]*?<header class="detail-head"[\s\S]*?<\/header>[\s\S]*?<main class="article-body">[\s\S]*?<\/main>[\s\S]*?<\/div>[\s\S]*?<aside class="reading-sidebar">/)
  assert.match(source, /\.detail-head\s*\{[^}]*position:\s*relative;/)
  assert.match(source, /\.detail-head\s*\{[^}]*margin-bottom:\s*30px;/)
  assert.match(source, /\.detail-head\s*\{[^}]*padding-bottom:\s*24px;/)
  assert.match(source, /\.detail-head\s*\{[^}]*border-bottom:\s*1px solid color-mix\(in srgb,\s*var\(--border-color\)\s*72%,\s*transparent\);/)
  assert.match(source, /\.detail-head\s*\{[^}]*background:\s*transparent;/)
  assert.match(source, /\.detail-head\s*\{[^}]*box-shadow:\s*none;/)
  assert.match(source, /\.detail-actions\s*\{[^}]*display:\s*flex;/)
  assert.match(source, /\.detail-actions\s*\{[^}]*margin-top:\s*20px;/)
  assert.doesNotMatch(source, /\.detail-actions\s*\{[^}]*border-bottom:/)
  assert.match(source, /\.favorite-button\s*\{[^}]*background:\s*color-mix\(in srgb,\s*var\(--panel-bg\)\s*78%,\s*transparent\);/)
  assert.doesNotMatch(source, /\.detail-head::before/)
  assert.doesNotMatch(source, /\.detail-head::after/)
  assert.doesNotMatch(source, /\.detail-head\s*\{[^}]*border-radius:/)
})

test('article detail summary reads as inline metadata instead of a card', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /class="detail-meta"[\s\S]*?字数 \{\{\s*readingStats\.wordCount\s*\}\}/)
  assert.match(source, /\.detail-meta\s*\{[^}]*display:\s*flex;/)
  assert.match(source, /\.detail-meta\s*\{[^}]*flex-wrap:\s*wrap;/)
  assert.match(source, /\.detail-meta\s*\{[^}]*gap:\s*8px 14px;/)
  assert.match(source, /\.detail-meta\s*\{[^}]*font-size:\s*13px;/)
  assert.doesNotMatch(source, /aria-label="文章阅读摘要"/)
  assert.doesNotMatch(source, /class="meta-line"/)
  assert.doesNotMatch(source, /\.detail-meta::before/)
  assert.doesNotMatch(source, /\.detail-meta\s*\{[^}]*border-radius:/)
  assert.doesNotMatch(source, /\.detail-meta\s*\{[^}]*border-left:/)
})

test('article detail keeps the article summary as a quiet title-area deck', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /<h1>\{\{\s*article\.title\s*\}\}<\/h1>[\s\S]*?<p v-if="article\.summary" class="detail-summary">\{\{\s*article\.summary\s*\}\}<\/p>[\s\S]*?<div class="detail-meta">/)
  assert.match(source, /\.detail-summary\s*\{[^}]*max-width:\s*680px;/)
  assert.match(source, /\.detail-summary\s*\{[^}]*margin:\s*0 0 20px;/)
  assert.match(source, /\.detail-summary\s*\{[^}]*font-size:\s*clamp\(16px,\s*1\.7vw,\s*18px\);/)
  assert.match(source, /\.detail-summary\s*\{[^}]*line-height:\s*1\.75;/)
  assert.doesNotMatch(source, /\.detail-summary\s*\{[^}]*background:/)
  assert.doesNotMatch(source, /\.detail-summary\s*\{[^}]*border:/)
  assert.doesNotMatch(source, /\.detail-summary\s*\{[^}]*border-radius:/)
})

test('article detail toc uses the prototype rail instead of card panels', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /\.reading-sidebar\s*\{[^}]*border-left:\s*1px solid color-mix\(in srgb,\s*var\(--border-color\)\s*72%,\s*transparent\);/)
  assert.match(source, /\.reading-sidebar\s*\{[^}]*padding-left:\s*18px;/)
  assert.match(source, /\.toc-panel\s*\{[^}]*background:\s*transparent;/)
  assert.match(source, /\.toc-panel\s*\{[^}]*box-shadow:\s*none;/)
  assert.match(source, /\.toc-link\.active\s*\{[^}]*background:\s*transparent;/)
  assert.doesNotMatch(source, /\.toc-panel\s*\{[^}]*border:\s*1px/)
  assert.doesNotMatch(source, /\.section-meter\b/)
  assert.doesNotMatch(source, /\.meter-dot\b/)
})

test('article detail continuation reads as an article epilogue instead of cards', () => {
  const source = read('../views/ArticleDetail.vue')

  assert.match(source, /class="article-epilogue"/)
  assert.match(source, /class="neighbor-direction"/)
  assert.match(source, /class="neighbor-link previous"/)
  assert.match(source, /class="neighbor-link next"/)
  assert.match(source, /class="related-index"/)
  assert.match(source, /class="related-link"/)
  assert.match(source, /\.article-epilogue\s*\{[^}]*background:\s*linear-gradient\(/)
  assert.match(source, /\.article-epilogue\s*\{[^}]*border-top:\s*1px solid color-mix\(in srgb,\s*var\(--border-color\)\s*70%,\s*transparent\);/)
  assert.match(source, /\.neighbor-direction\s*\{[^}]*font-family:\s*var\(--font-mono\);/)
  assert.match(source, /\.neighbor-link,\s*\.related-link\s*\{[^}]*border:\s*0;/)
  assert.match(source, /\.neighbor-link,\s*\.related-link\s*\{[^}]*border-radius:\s*var\(--radius-sm\);/)
  assert.match(source, /\.neighbor-link,\s*\.related-link\s*\{[^}]*background:\s*transparent;/)
  assert.match(source, /\.neighbor-link,\s*\.related-link\s*\{[^}]*box-shadow:\s*none;/)
  assert.match(source, /\.related-index\s*\{[^}]*font-family:\s*var\(--font-mono\);/)
  assert.match(source, /\.related-list\s*\{[^}]*border-top:\s*1px solid color-mix\(in srgb,\s*var\(--border-color\)\s*58%,\s*transparent\);/)
  assert.doesNotMatch(source, /class="neighbor-card/)
  assert.doesNotMatch(source, /class="related-card/)
  assert.doesNotMatch(source, /\.neighbor-card\b/)
  assert.doesNotMatch(source, /\.related-card\b/)
})

test('reading space uses continuation-focused visual classes', () => {
  const source = read('../views/ReadingSpace.vue')

  assert.match(source, /reading-main::before/)
  assert.match(source, /\.continue-panel::after/)
  assert.match(source, /progress-track/)
  assert.match(source, /theme-glow-color/)
  assert.doesNotMatch(source, /reading-progress-track/)
})

test('reading space keeps the canvas neon wave compact theme-aware and lightly drifting', () => {
  const source = read('../views/ReadingSpace.vue')

  assert.match(source, /class="signal-wave"/)
  assert.match(source, /ref="signalCanvas"/)
  assert.match(source, /class="signal-canvas"/)
  assert.match(source, /@pointerenter\.stop="enterSignalCanvas"/)
  assert.match(source, /@pointermove\.stop="moveSignalCanvas"/)
  assert.match(source, /@pointerleave\.stop="leaveSignalCanvas"/)
  assert.match(source, /const WAVE_FREQUENCY = 0\.036/)
  assert.match(source, /const WAVE_AMPLITUDE = 34/)
  assert.match(source, /const WAVE_TOP_PADDING = 14/)
  assert.match(source, /const CURSOR_RADIUS = 150/)
  assert.match(source, /const CURSOR_LIFT = 40/)
  assert.match(source, /const PARTICLE_MAX = 18/)
  assert.match(source, /const PARTICLE_LIFETIME = 2200/)
  assert.match(source, /const PARTICLE_MIN_PER_BURST = 1/)
  assert.match(source, /const PARTICLE_MAX_PER_BURST = 2/)
  assert.match(source, /const PARTICLE_SPAWN_INTERVAL = 180/)
  assert.match(source, /let lastParticleSpawn = 0/)
  assert.match(source, /function randomNoise/)
  assert.match(source, /createLinearGradient\(0,\s*0,\s*width,\s*0\)/)
  assert.match(source, /const waveColors = getSignalWaveColors\(canvas\)/)
  assert.match(source, /gradient\.addColorStop\(0,\s*waveColors\.start\)/)
  assert.match(source, /gradient\.addColorStop\(1,\s*waveColors\.end\)/)
  assert.match(source, /function getSignalWaveColors/)
  assert.match(source, /--signal-wave-start/)
  assert.match(source, /--signal-wave-end/)
  assert.match(source, /--signal-wave-glow/)
  assert.match(source, /ctx\.lineWidth = 1\.25/)
  assert.match(source, /Math\.sin\(\(x \+ time\) \* WAVE_FREQUENCY\) \* WAVE_AMPLITUDE/)
  assert.match(source, /Math\.exp\(-\(distance \* distance\) \/ \(2 \* sigma \* sigma\)\)/)
  assert.match(source, /cursor\.active && distance <= CURSOR_RADIUS/)
  assert.match(source, /y = applySignalCursorLift\(y,\s*CURSOR_LIFT \* gaussian\)/)
  assert.match(source, /function applySignalCursorLift\(y,\s*desiredLift\)/)
  assert.match(source, /return WAVE_TOP_PADDING \+ availableLift \* Math\.exp\(-desiredLift \/ availableLift\)/)
  assert.match(source, /spawnWaveParticles\(peaks,\s*gradient,\s*timestamp,\s*width\)/)
  assert.match(source, /timestamp - lastParticleSpawn < PARTICLE_SPAWN_INTERVAL/)
  assert.match(source, /const count = randomBetween\(PARTICLE_MIN_PER_BURST,\s*PARTICLE_MAX_PER_BURST\)/)
  assert.match(source, /const speed = 0\.008 \+ Math\.random\(\) \* 0\.018/)
  assert.match(source, /size:\s*1 \+ Math\.random\(\) \* 1\.2/)
  assert.match(source, /ctx\.globalAlpha = alpha \* 0\.38/)
  assert.match(source, /particles\.splice\(0,\s*particles\.length - PARTICLE_MAX\)/)
  assert.match(source, /requestAnimationFrame\(drawSignalCanvas\)/)
  assert.match(source, /\.signal-wave\s*\{[^}]*bottom:\s*18px;[^}]*height:\s*104px;[^}]*background:\s*transparent;[^}]*pointer-events:\s*auto;/)
  assert.doesNotMatch(source, /\.signal-wave\s*\{(?:(?!\}).)*border:/s)
  assert.doesNotMatch(source, /\.signal-wave\s*\{(?:(?!\}).)*box-shadow:/s)
  assert.match(source, /\.signal-canvas\s*\{[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*filter:\s*drop-shadow/)
  assert.doesNotMatch(source, /gradient\.addColorStop\(0,\s*'#00d4ff'\)/)
  assert.doesNotMatch(source, /gradient\.addColorStop\(1,\s*'#7b2ffc'\)/)
  assert.doesNotMatch(source, /const WAVE_FREQUENCY = 0\.02/)
  assert.doesNotMatch(source, /const WAVE_AMPLITUDE = 24/)
  assert.doesNotMatch(source, /const WAVE_AMPLITUDE = 60/)
  assert.doesNotMatch(source, /y -= CURSOR_LIFT \* gaussian/)
  assert.doesNotMatch(source, /const PARTICLE_MIN_PER_FRAME = 5/)
  assert.doesNotMatch(source, /const PARTICLE_MAX_PER_FRAME = 8/)
  assert.doesNotMatch(source, /ctx\.shadowBlur = cursor\.active \? 18 : 10/)
  assert.match(source, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.signal-canvas[\s\S]*?\{[^}]*display:\s*none;/)
  assert.doesNotMatch(source, /class="wave-svg"/)
  assert.doesNotMatch(source, /class="surface-line/)
  assert.doesNotMatch(source, /class="wave-path/)
  assert.doesNotMatch(source, /surfaceWavePath/)
  assert.doesNotMatch(source, /surfaceLifts/)
  assert.doesNotMatch(source, /waveScan/)
  assert.doesNotMatch(source, /stroke-width:\s*8px;/)
  assert.doesNotMatch(source, /kinetic-toy/)
  assert.doesNotMatch(source, /toy-thread/)
  assert.doesNotMatch(source, /toy-chip/)
  assert.doesNotMatch(source, /toy-orbit/)
  assert.doesNotMatch(source, /moveKineticToy/)
  assert.doesNotMatch(source, /--toy-a-x/)
  assert.doesNotMatch(source, /liquid-playground/)
  assert.doesNotMatch(source, /liquid-surface/)
  assert.doesNotMatch(source, /liquid-ripple/)
  assert.doesNotMatch(source, /liquid-glow/)
  assert.doesNotMatch(source, /liquid-current/)
  assert.doesNotMatch(source, /updateLiquidPool/)
  assert.doesNotMatch(source, /--pool-cursor-x/)
  assert.doesNotMatch(source, /magnetic-field/)
  assert.doesNotMatch(source, /magnetic-particle/)
  assert.doesNotMatch(source, /fieldBreath/)
  assert.doesNotMatch(source, /magneticFloat/)
  assert.doesNotMatch(source, /reading-pulse/)
  assert.doesNotMatch(source, /pulse-track/)
  assert.doesNotMatch(source, /--pulse-progress/)
  assert.doesNotMatch(source, /overview\.historyTotal[\s\S]{0,700}signal-wave/)
  assert.doesNotMatch(source, /overview\.favoriteTotal[\s\S]{0,700}signal-wave/)
})

test('reading space uses the private reading prototype skeleton', () => {
  const source = read('../views/ReadingSpace.vue')

  assert.match(source, /class="page-head"/)
  assert.match(source, /class="head-meta"/)
  assert.match(source, /Reading desk/)
  assert.match(source, /我的阅读更像一个安静的续接台/)
  assert.match(source, /class="reading-layout"/)
  assert.match(source, /class="continue-panel"/)
  assert.match(source, /class="progress-block"/)
  assert.match(source, /class="progress-label"/)
  assert.match(source, /class="progress-track"/)
  assert.match(source, /class="continue-actions"/)
  assert.match(source, /to="\/reading\/history"/)
  assert.match(source, /class="reading-side"/)
  assert.match(source, /class="timeline"/)
  assert.match(source, /class="timeline-item/)
  assert.match(source, /class="favorite-index"/)
  assert.match(source, /\.head-meta\s*\{[^}]*background:\s*var\(--panel-bg\)/)
  assert.match(source, /\.head-meta\s*\{[^}]*border:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.head-meta\s*\{[^}]*border-radius:\s*var\(--radius-md\)/)
  assert.match(source, /\.head-meta\s*\{[^}]*display:\s*grid;/)
  assert.match(source, /\.meta-line\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto;/)
  assert.match(source, /\.meta-label\s*\{[^}]*color:\s*var\(--muted-text-color\)/)
  assert.match(source, /\.meta-value\s*\{[^}]*font-size:\s*18px;/)
  assert.match(source, /\.meta-value\s*\{[^}]*font-weight:\s*800;/)
  assert.match(source, /\.meta-value\s*\{[^}]*text-align:\s*right;/)
  assert.doesNotMatch(source, /\.meta-line\s*\{[^}]*border-bottom:/)
  assert.match(source, /\.reading-side\s*\{[\s\S]*border:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.timeline\s*\{[\s\S]*border-left:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.timeline-item::before/)
  assert.match(source, /\.favorite-index\s*\{[\s\S]*border-top:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.favorite-line\s*\{[\s\S]*padding:\s*14px 0/)
  assert.match(source, /@media\s*\(max-width:\s*980px\)[\s\S]*?\.page-head,\s*\.reading-layout\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*1fr\);/)
  assert.match(source, /@media\s*\(max-width:\s*480px\)[\s\S]*?\.meta-line\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
  assert.doesNotMatch(source, /class="page-heading"/)
  assert.doesNotMatch(source, /class="section-heading"/)
  assert.doesNotMatch(source, /last-read-section/)
  assert.doesNotMatch(source, /class="continue-cover"/)
  assert.doesNotMatch(source, /class="favorite-cover"/)
  assert.doesNotMatch(source, /class="reading-section"/)
  assert.doesNotMatch(source, /continue-panel::before/)
  assert.doesNotMatch(source, /favorite-line::before/)
})

test('reading history and favorites share the private index skeleton', () => {
  const history = read('../views/ReadingHistory.vue')
  const favorites = read('../views/Favorites.vue')

  assert.match(history, /class="page-head"/)
  assert.match(history, /class="head-meta"/)
  assert.match(history, /class="history-timeline"/)
  assert.match(history, /class="timeline-group"/)
  assert.match(history, /class="clear-button"/)
  assert.doesNotMatch(history, /class="page-heading"/)

  assert.match(favorites, /class="page-head"/)
  assert.match(favorites, /class="head-meta"/)
  assert.match(favorites, /class="creator-toolbar"/)
  assert.match(favorites, /class="favorite-index"/)
  assert.match(favorites, /class="back-to-reading"/)
  assert.doesNotMatch(favorites, /class="page-heading"/)
  assert.doesNotMatch(favorites, /class="filter-toolbar"/)
  assert.doesNotMatch(favorites, /class="favorite-list"/)
})

test('reading history summary uses a solid action card', () => {
  const history = read('../views/ReadingHistory.vue')

  assert.match(history, /\.head-meta\s*\{[^}]*display:\s*grid;/)
  assert.match(history, /\.head-meta\s*\{[^}]*background:\s*var\(--panel-bg\)/)
  assert.match(history, /\.head-meta\s*\{[^}]*border:\s*1px solid var\(--border-color\)/)
  assert.match(history, /\.head-meta\s*\{[^}]*border-radius:\s*var\(--radius-md\)/)
  assert.match(history, /\.head-meta\s*\{[^}]*box-shadow:\s*var\(--shadow-soft\)/)
  assert.match(history, /\.meta-line\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto;/)
  assert.match(history, /\.meta-label\s*\{[^}]*color:\s*var\(--muted-text-color\)/)
  assert.match(history, /\.meta-value\s*\{[^}]*font-size:\s*18px;/)
  assert.match(history, /\.meta-value\s*\{[^}]*font-weight:\s*800;/)
  assert.match(history, /\.clear-button\s*\{[^}]*margin-top:\s*6px;/)
  assert.doesNotMatch(history, /\.head-meta\s*\{[^}]*border-left:/)
  assert.doesNotMatch(history, /\.meta-line\s*\{[^}]*border-bottom:/)
})

test('reading space isolates its fixed continuation backdrop', () => {
  const source = read('../views/ReadingSpace.vue')

  assert.match(source, /\.reading-main\s*\{(?=[^}]*position:\s*relative;)(?=[^}]*isolation:\s*isolate;)[^}]*\}/)
})

test('reading space decorative continuation line ignores pointer events', () => {
  const source = read('../views/ReadingSpace.vue')

  assert.match(source, /\.continue-panel::after\s*\{[\s\S]*?pointer-events:\s*none;/)
})

test('creator article workspace uses control-console visual treatment', () => {
  const source = read('../views/creator/MyArticles.vue')

  assert.match(source, /creator-shell/)
  assert.match(source, /class="page-head"/)
  assert.match(source, /class="head-meta"/)
  assert.match(source, /class="creator-toolbar"/)
  assert.match(source, /class="searchbox"/)
  assert.match(source, /class="status-filters"/)
  assert.match(source, /class="creator-workspace"/)
  assert.match(source, /class="group-rail"/)
  assert.match(source, /class="article-flow-panel"/)
  assert.match(source, /class="creator-list"/)
  assert.match(source, /class="creator-article-card/)
  assert.match(source, /class="row-meta"/)
  assert.match(source, /class="row-actions"/)
  assert.match(source, /\.group-item::before/)
  assert.match(source, /\.head-meta\s*\{[\s\S]*border:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.head-meta\s*\{[\s\S]*box-shadow:\s*var\(--shadow-soft\)/)
  assert.match(source, /\.article-flow-panel\s*\{[\s\S]*border:\s*1px solid var\(--border-color\)/)
  assert.match(source, /\.creator-article-card::before/)
  assert.match(source, /\.creator-article-card:not\(\.is-empty-card\):hover/)
  assert.match(source, /status-pill/)
  assert.doesNotMatch(source, /class="page-header"/)
  assert.doesNotMatch(source, /class="workspace"/)
  assert.doesNotMatch(source, /class="group-panel"/)
  assert.doesNotMatch(source, /class="table-wrap"/)
  assert.doesNotMatch(source, /class="article-row"/)
  assert.doesNotMatch(source, /class="table-head"/)
  assert.doesNotMatch(source, /class="article-primary-action"/)
  assert.doesNotMatch(source, /<el-table\b/)
  assert.doesNotMatch(source, /#2f80ed/)
  assert.doesNotMatch(source, /#7c5cff/)
})

test('secondary public and auth pages no longer expose legacy visual shells', () => {
  const tagArticles = read('../views/TagArticles.vue')
  const login = read('../views/Login.vue')
  const register = read('../views/Register.vue')

  assert.match(tagArticles, /class="tag-shell"/)
  assert.match(tagArticles, /class="page-head"/)
  assert.match(tagArticles, /class="head-meta"/)
  assert.match(tagArticles, /class="article-stream"/)
  assert.doesNotMatch(tagArticles, /tag-page-head/)

  for (const source of [login, register]) {
    assert.match(source, /class="auth-shell"/)
    assert.match(source, /class="auth-panel"/)
    assert.match(source, /class="auth-index"/)
    assert.match(source, /class="eyebrow"/)
    assert.doesNotMatch(source, /<el-card\b/)
    assert.doesNotMatch(source, /auth-card/)
  }
})

test('login page explains the destination after authentication', () => {
  const login = read('../views/Login.vue')

  assert.match(login, /登录后继续/)
  assert.match(login, /接上刚才的阅读和创作。/)
  assert.match(login, /登录后会优先回到你刚才要打开的页面/)
  assert.match(login, /继续上次阅读位置/)
  assert.match(login, /仅管理员可进入/)
  assert.match(login, /登录后继续访问刚才的页面/)
  assert.doesNotMatch(login, /私人入口/)
  assert.doesNotMatch(login, /回到你的知识空间。/)
  assert.doesNotMatch(login, /进入后台，继续管理你的内容。/)
})

test('creator writing and preview pages use the prototype surface system', () => {
  const write = read('../views/creator/ArticleWrite.vue')
  const preview = read('../views/creator/ArticlePreview.vue')

  assert.match(write, /class="compose-shell"/)
  assert.match(write, /class="page-head"/)
  assert.match(write, /class="rail-panel preflight-panel"/)
  assert.match(write, /class="preflight-head"/)
  assert.match(write, /class="preflight-dots"/)
  assert.match(write, /class="preflight-token/)
  assert.match(write, /class="draft-stats"/)
  assert.match(write, /preflightChecks/)
  assert.match(write, /preflightReadyCount/)
  assert.match(write, /writingStats/)
  assert.match(write, /getReadingStats/)
  assert.match(write, /class="compose-grid"/)
  assert.match(write, /class="compose-panel"/)
  assert.match(write, /class="compose-rail"/)
  assert.doesNotMatch(write, /class="head-meta preflight-panel"/)
  assert.doesNotMatch(write, /class="meta-line"/)
  assert.doesNotMatch(write, /grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(260px,\s*340px\)/)
  assert.doesNotMatch(write, /class="page-header"/)
  assert.doesNotMatch(write, /\.page-header/)

  assert.match(preview, /class="detail-head preview-head"/)
  assert.match(preview, /<p v-if="article\.summary" class="detail-summary">\{\{\s*article\.summary\s*\}\}<\/p>[\s\S]*?<div class="detail-meta">/)
  assert.match(preview, /class="reading-canvas preview-reading-layout"/)
  assert.match(preview, /class="reading-primary"/)
  assert.match(preview, /class="article-body preview-body"/)
  assert.match(preview, /class="mobile-toc"/)
  assert.match(preview, /class="reading-sidebar preview-sidebar"/)
  assert.match(preview, /class="toc-panel"/)
  assert.match(preview, /class="note-panel"/)
  assert.match(preview, /\.reading-canvas\.has-toc\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*760px\)\s+280px;/)
  assert.match(preview, /\.reading-sidebar\s*\{[^}]*border-left:\s*1px solid color-mix\(in srgb,\s*var\(--border-color\)\s*72%,\s*transparent\);/)
  assert.match(preview, /\.toc-panel\s*\{[^}]*border:\s*0;/)
  assert.match(preview, /\.toc-panel\s*\{[^}]*background:\s*transparent;/)
  assert.match(preview, /\.toc-panel\s*\{[^}]*box-shadow:\s*none;/)
  assert.match(preview, /\.toc-link\.active\s*\{[^}]*background:\s*transparent;/)
  assert.doesNotMatch(preview, /aria-label="预览摘要"/)
  assert.doesNotMatch(preview, /class="meta-line"/)
  assert.doesNotMatch(preview, /class="section-meter"/)
  assert.doesNotMatch(preview, /class="meter-dot"/)
  assert.doesNotMatch(preview, /\.meta-line/)
  assert.doesNotMatch(preview, /\.toc-panel,\s*\n\s*\.section-meter/)
  assert.doesNotMatch(preview, /\.toc-panel\s*\{[^}]*border:\s*1px solid/)
  assert.doesNotMatch(preview, /preview-head,\s*\n\s*\.preview-body,[\s\S]*background:\s*var\(--panel-bg\)/)
})

test('admin layout uses the backend management prototype frame and merged resource entry', () => {
  const layout = read('../components/admin/AdminLayout.vue')
  const router = read('../router/index.js')

  assert.match(layout, /class="admin-frame"/)
  assert.match(layout, /class="admin-sidebar"/)
  assert.match(layout, /class="brand-lockup"/)
  assert.match(layout, /class="nav-stack"/)
  assert.match(layout, /管理中枢/)
  assert.match(layout, /to="\/admin\/resources"/)
  assert.match(layout, /资源管理/)
  assert.match(layout, /class="main-surface"/)
  assert.match(layout, /class="topbar"/)
  assert.match(layout, /class="tool-button/)
  assert.doesNotMatch(layout, /Blog Admin/)
  assert.doesNotMatch(layout, /#172334/)
  assert.doesNotMatch(layout, /<el-container\b/)
  assert.doesNotMatch(layout, /<el-menu\b/)
  assert.doesNotMatch(layout, /\/admin\/tags[\s\S]{0,80}标签管理/)
  assert.doesNotMatch(layout, /\/admin\/images[\s\S]{0,80}图片管理/)

  assert.match(router, /path:\s*'resources'[\s\S]*Resources\.vue/)
  assert.match(router, /path:\s*'tags'[\s\S]{0,80}redirect:\s*'\/admin\/resources'/)
  assert.match(router, /path:\s*'images'[\s\S]{0,80}redirect:\s*'\/admin\/resources'/)
})

test('admin article management uses the prototype list rows instead of element tables', () => {
  const source = read('../views/admin/Articles.vue')

  assert.match(source, /class="page-head"/)
  assert.match(source, /class="surface article-board"/)
  assert.match(source, /class="help-popover"/)
  assert.match(source, /class="help-trigger"/)
  assert.match(source, /class="help-card"/)
  assert.match(source, /class="filter-bar"/)
  assert.match(source, /class="article-table-head"/)
  assert.match(source, /class="article-row/)
  assert.match(source, /class="article-state/)
  assert.match(source, /class="state-dot"/)
  assert.match(source, /class="visibility-mark/)
  assert.match(source, /class="visibility-icon"/)
  assert.match(source, /class="row-actions"/)
  assert.match(source, /class="row-action-button/)
  assert.match(source, /reviewReason/)
  assert.match(source, /articleVisibilityText/)
  assert.doesNotMatch(source, /<el-table\b/)
  assert.doesNotMatch(source, /<el-table-column\b/)
  assert.doesNotMatch(source, /class="admin-toolbar"/)
})

test('admin resources merges tag and image management into one prototype board', () => {
  assert.ok(exists('../views/admin/Resources.vue'))
  const source = read('../views/admin/Resources.vue')

  assert.match(source, /class="page-head"/)
  assert.match(source, /class="resource-summary"/)
  assert.match(source, /class="resource-tile"/)
  assert.match(source, /class="resource-board"/)
  assert.match(source, /class="surface"/)
  assert.match(source, /class="inline-create"/)
  assert.match(source, /class="tag-list"/)
  assert.match(source, /class="tag-item"/)
  assert.match(source, /class="mini-image-grid"/)
  assert.match(source, /class="image-card"/)
  assert.match(source, /class="mini-image"/)
  assert.match(source, /getTags/)
  assert.match(source, /getImages/)
  assert.match(source, /createTag/)
  assert.match(source, /deleteTag/)
  assert.match(source, /deleteImage/)
  assert.doesNotMatch(source, /<el-table\b/)
  assert.doesNotMatch(source, /<el-table-column\b/)
})

test('admin dashboard users profile and editor share the prototype surface system', () => {
  const dashboard = read('../views/admin/Dashboard.vue')
  const users = read('../views/admin/Users.vue')
  const profile = read('../views/admin/Profile.vue')
  const editor = read('../views/admin/ArticleEdit.vue')

  assert.match(dashboard, /class="signal-strip"/)
  assert.match(dashboard, /class="surface"/)
  assert.match(dashboard, /class="status-ledger"/)
  assert.match(dashboard, /class="review-list"/)
  assert.doesNotMatch(dashboard, /class="stat-card"/)

  assert.match(users, /class="page-head"/)
  assert.match(users, /class="surface"/)
  assert.match(users, /class="help-popover"/)
  assert.match(users, /class="row-list"/)
  assert.match(users, /class="data-row"/)
  assert.match(users, /class="row-action-button/)
  assert.doesNotMatch(users, /<el-table\b/)
  assert.doesNotMatch(users, /<el-table-column\b/)

  assert.match(profile, /class="profile-layout"/)
  assert.match(profile, /class="profile-mark"/)
  assert.match(profile, /class="info-grid"/)
  assert.match(profile, /class="info-item"/)
  assert.doesNotMatch(profile, /<el-descriptions\b/)

  assert.match(editor, /class="page-head"/)
  assert.match(editor, /class="editor-layout"/)
  assert.match(editor, /class="editor-panel"/)
  assert.match(editor, /class="tool-button/)
  assert.doesNotMatch(editor, /<h2>\{\{ isEdit/)
})

test('primary page summaries use index rails instead of card shells', () => {
  const indexedPages = [
    read('../views/Favorites.vue')
  ]
  const readingSpace = read('../views/ReadingSpace.vue')
  const readingHistory = read('../views/ReadingHistory.vue')

  for (const source of indexedPages) {
    assert.match(source, /\.head-meta\s*\{[\s\S]*border-left:\s*1px solid var\(--border-color\)/)
    assert.doesNotMatch(source, /\.head-meta\s*\{[^}]*border-radius/)
    assert.doesNotMatch(source, /\.head-meta\s*\{[^}]*box-shadow/)
    assert.doesNotMatch(source, /\.head-meta\s*\{[^}]*background:\s*color-mix/)
  }

  assert.match(readingSpace, /\.head-meta\s*\{[^}]*background:\s*var\(--panel-bg\)/)
  assert.match(readingSpace, /\.head-meta\s*\{[^}]*border-radius:\s*var\(--radius-md\)/)
  assert.match(readingSpace, /\.head-meta\s*\{[^}]*box-shadow:\s*var\(--shadow-soft\)/)
  assert.match(readingHistory, /\.head-meta\s*\{[^}]*background:\s*var\(--panel-bg\)/)
  assert.match(readingHistory, /\.head-meta\s*\{[^}]*border-radius:\s*var\(--radius-md\)/)
  assert.match(readingHistory, /\.head-meta\s*\{[^}]*box-shadow:\s*var\(--shadow-soft\)/)
})
